[package]
name = "sum-tree"
version = "1.0.0"
authors = ["Eduardo Bonilha <eduardo@hackachain.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
borsh = "0.8.1"
